### ISSUE TITLE
Can't install ooyala player

### ISSUE THREAD

**Issue by wzymaster** [edx-solutions/xblock-ooyala#60]
I followed the instruction to do pip install  and enable it in advanced module, however, I always get such error :  

"Your policy changes have been saved.
Please note that validation of your policy key and value pairs is not currently in place yet. If you are having difficulties, please review your policy pairs."

![screen shot 2015-02-16 at 11 26 40 am](https://cloud.githubusercontent.com/assets/2967108/6215446/b8002cd8-b5ce-11e4-8034-e78acec2d850.png)

**Comment by antoviaque** [comment]
@wzymaster That seem like it went ok, that message is only a warning and isn't related to the change you're making. Are you able to add the Ooyala player in the course afterwards?

**Comment by wzymaster** [comment]
No, I am not able to see Ooyala player in adding a unit  in a course.

**Comment by wzymaster** [comment]
Can you tell me how to verify if Ooyala player is installed and set up correctly ?

**Comment by antoviaque** [comment]
@wzymaster If there is an issue with the XBlock, you should usually see it in the logs while starting the LMS. Also make sure you have it in the virtualenv used by the edxapp services.

Are you using devstack or is this on a production instance? Make sure you have 

```FEATURES['ALLOW_ALL_ADVANCED_COMPONENTS'] = True```

and refer to https://github.com/edx/edx-platform/wiki/Installing-a-new-XBlock for the installation steps
