### ISSUE TITLE
Xblock doesn't appear in "Advanced" tab

### ISSUE THREAD

**Issue by phuongtailtranminh** [edx-solutions/xblock-ooyala#65]
Hi,

I'm trying to install this xblock (xblock-ooyala).

The installation is fine. But after that, I don't see this xblock in "Advanced" tab.

I tried with "xblock-brightcove " and "videojs" and these work fine.

**Comment by naeem91** [comment]
Hi,
Make sure you have "ooyala-player" in Advanced Module List in Advanced Settings.

**Comment by phuongtailtranminh** [comment]
Yes. I have it

**Comment by naeem91** [comment]
Did you install it in right virtual environment? As `edxapp` user what is the output of 

> pip show xblock-ooyala-player
